version: '3.5'

services:
  gs-rest-service:
    image: nem75/gs-rest-service:{{nem75:gs-rest-service}}
    ports:
      - "8080:8080"
  postgres:
    image: postgres:11-alpine
    hostname: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: gs_rest_service
      POSTGRES_DB: gs_rest_service
  adminer:
    image: adminer
    ports:
      - 8081:8080
